README.md
log-viewer/.README.j2
log-viewer/Dockerfile
log-viewer/config.json

- Enables user authentication in configuration
N/A

🔒Enables user authentication

---

.github/support.yml
.gitlab-ci.yml
README.md
log-viewer/.README.j2
log-viewer/Dockerfile
log-viewer/build.json
log-viewer/config.json
log-viewer/rootfs/etc/cont-init.d/10-requirements.sh

See commit messages for details of what has been done.
N/A
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

Base upgrade and features

---

log-viewer/Dockerfile

Upgrade lua-resty-http to 0.13-r0
None

:arrow_up:  Upgrade lua-resty-http to 0.13-r0

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrade add-on base image to 9.1.0

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrade add-on base image to 9.1.1

---

log-viewer/Dockerfile
log-viewer/build.json

https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2

Upgrade add-on base image to 9.1.2

---

log-viewer/Dockerfile

:arrow_up: Upgrades git to 2.30.1-r0

---

log-viewer/Dockerfile

:arrow_up: Upgrades nodejs to 14.15.5-r0

---

log-viewer/Dockerfile

:arrow_up: Upgrades nodejs to 14.16.0-r0

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v9.1.5

:arrow_up: Upgrades add-on base image to v9.1.5

---

log-viewer/Dockerfile

⬆️ Upgrades git to 2.30.2-r0

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 14.16.1-r0

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v9.1.7

⬆️ Upgrades add-on base image to v9.1.7

---

.github/workflows/deploy.yaml

Old school slug mess, needs fixing 😬 
Fixes #62

🚑  Fix deployment of add-on

---

.github/workflows/deploy.yaml

Because the previous PR factually didn't change anything 🤦

:ambulance: Fix deployment of add-on (again)

---

log-viewer/rootfs/etc/nginx/templates/ingress.gtpl

Fixes missing rewrite rules for Ingress support that got lost in the NGinx configuration refactoring.

🚑  Fix deployment of add-on (again)

---

log-viewer/Dockerfile

> (Describe the changes and rationale behind them)
> ([Github link][autolink-references] to related issues or pull requests)
[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

⬆️ Upgrades nodejs to 14.16.1-r1

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v9.2.0

⬆️ Upgrades add-on base image to v9.2.0

---

log-viewer/rootfs/etc/nginx/nginx.conf

Remove NGINX access log from Supervisor log output

---

log-viewer/translations/en.yaml

Add translation support

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v9.2.1

⬆️ Upgrades add-on base image to v9.2.1

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v9.2.2

⬆️ Upgrades add-on base image to v9.2.2

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to v10.0.0

⬆️ Upgrades add-on base image to v10.0.0

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 14.17.4-r0

---

log-viewer/config.json

🏎 Enable streaming mode for Ingress

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 14.17.6-r0

---

log-viewer/Dockerfile
log-viewer/build.json

Upgrades add-on base image to 10.1.0

⬆️ Upgrades add-on base image to 10.1.0

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 14.18.1-r0

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 10.2.0

⬆️ Upgrades add-on base image to 10.2.0

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 10.2.2

⬆️ Upgrades add-on base image to 10.2.2

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 11.0.0

⬆️ Upgrades add-on base image to 11.0.0

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 16.13.2-r0

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 11.0.1

⬆️ Upgrades add-on base image to 11.0.1

---

log-viewer/Dockerfile

⬆️ Upgrades nodejs to 16.14.0-r0

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 11.1.0

⬆️ Upgrades add-on base image to 11.1.0

---

.github/workflows/deploy.yaml
log-viewer/build.yaml
log-viewer/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

log-viewer/DOCS.md

Add Home Assistant my buttons to the add-on documentation, making it easier to find the add-on.

:books: Add My buttons to documentation

---

log-viewer/Dockerfile
log-viewer/build.yaml
log-viewer/rootfs/etc/cont-init.d/nginx.sh
log-viewer/rootfs/etc/services.d/logviewer/finish
log-viewer/rootfs/etc/services.d/logviewer/run
log-viewer/rootfs/etc/services.d/nginx/finish
log-viewer/rootfs/etc/services.d/nginx/run

Upgrades add-on base image to 12.0.0

⬆️ Upgrades add-on base image to 12.0.0

---

log-viewer/DOCS.md

Making things just a little bit easier

:books: Use new My Home Assistant link format

---

log-viewer/Dockerfile
log-viewer/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

LICENSE.md
README.md
log-viewer/.README.j2
log-viewer/DOCS.md

:fireworks: Updates maintenance/license year to 2023

---

log-viewer/Dockerfile

Remove unsafe perm from npm

---

README.md
log-viewer/build.yaml
log-viewer/config.yaml

Drop support for armhf & i386

---

log-viewer/config.yaml
log-viewer/rootfs/etc/services.d/logviewer/run

Migrate add-on to new Home Assistant configuration mapping

---

LICENSE.md
README.md
log-viewer/.README.j2
log-viewer/DOCS.md

:fireworks: Updates maintenance/license year to 2024
